[package]
name = "nearest_neighbor"
version = "0.1.0"
edition = "2021"
default-run = "nearest_neighbor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clap = {version="3.1.8", features=["derive"]}
serde = {version="1.0.136", features=["derive"]}
serde_json = "1.0.79"
mongodb = "2.1.0"
tokio = "1.17.0"
loadenv = "0.1.4"
bson = "2.1.0"
futures = "0.3.21"